# Generated by Django 4.2.2 on 2023-07-13 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_number', models.CharField(blank=True, default='#', max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('complaint_date', models.DateField()),
                ('complaint_detail', models.TextField(blank=True, null=True)),
                ('incident_category', models.CharField(blank=True, default='#', max_length=100, null=True)),
                ('incident_subcategory', models.CharField(blank=True, default='#', max_length=100, null=True)),
                ('customer_zip', models.CharField(blank=True, default='#', max_length=100, null=True)),
                ('customer_state', models.CharField(blank=True, default='#', max_length=50, null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=100)),
                ('intake_channel', models.CharField(blank=True, choices=[('Web', 'Web'), ('Email', 'Email'), ('Phone', 'Phone')], default='#', max_length=100, null=True)),
                ('company', models.CharField(blank=True, default='#', max_length=100, null=True)),
                ('agent_id', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=100)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='app.ticket')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
