# Generated by Django 4.2.2 on 2023-07-13 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='complaint_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 4, 20, 36, 16)),
        ),
    ]
