# Generated by Django 4.2.2 on 2023-07-15 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_ticket_complaint_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_date', models.DateField()),
                ('url_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='complaint_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 21, 14, 38, 14)),
        ),
    ]
